### ISSUE TITLE
TechCrunchのタイトル取得に失敗する

### ISSUE THREAD

**Issue by gmkou** [gmkou/FikaNote#86]
```
$ python
Python 2.7.10 (default, Nov  5 2015, 19:36:17) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('http://jp.techcrunch.com/2015/06/16/20150613in-the-future-employees-wont-exist/', None, headers = {'User-Agent' : 'Mozilla/5.0'})
>>> res = urllib2.urlopen(req)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by gmkou** [comment]
Python3にしたら解決するか？んなわけないかな。

**Comment by sassy** [comment]
そもそもなぜ502?
TechCrunchのサイト内の呼び出すリソースに502のものがある？

**Comment by gmkou** [comment]
それがまだ確認できていないです。

Wireshark動かしたかったけど、起動しなかった。
http://blog.pg1x.com/entry/2014/07/08/231557

brewで入るようになったみたいなのでインストール中
http://qiita.com/isaoshimizu/items/da3e74d5a8e9b1d6b6a4

**Comment by gmkou** [comment]
wiresharkでのキャプチャ結果を追加。fikanoteへのリクエストや、wgetでのtechcrunchへのリクエストはうまくいくのでGET時の差分か？

[request-to-fikanote.pcapng.zip](https://github.com/gmkou/FikaNote/files/77947/request-to-fikanote.pcapng.zip)
[request-to-techcrunch.pcapng.zip](https://github.com/gmkou/FikaNote/files/77946/request-to-techcrunch.pcapng.zip)
[wget-to-techcrunch.pcapng.zip](https://github.com/gmkou/FikaNote/files/77951/wget-to-techcrunch.pcapng.zip)

**Comment by sassy** [comment]
urllib2関係のデバッグ大変だな。
![komarigao](http://pic.prepics-cdn.com/shisan0509/25989000.jpeg)

techcrunch本体じゃなくて、
techcrunchが参照するinclusionの問題だったりしません？

**Comment by gmkou** [comment]
どうやらAcceptヘッダを付与しないとエラー吐く模様。付与したらうまくいく。

```
$ python
Python 2.7.10 (default, Nov  5 2015, 19:36:17) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('http://jp.techcrunch.com/2015/06/16/20150613in-the-future-employees-wont-exist/', None)
>>> req.add_header("Accept" , "*/*")
>>> res = urllib2.urlopen(req)
>>> res.info().getheader('content-type')
'text/html; charset=UTF-8'
```

**Comment by gmkou** [comment]
Merged.

**Comment by gmkou** [comment]
修正を入れたが機能していないので再度オープン。
